/* import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className="relative">
        <div className="absolute inset-0 z-0 bg-[url(/background5.png)] bg-cover bg-no-repeat bg-center" />
        <div className="absolute inset-0 z-10 bg-black/50 pointer-events-none" />
        <main className="relative z-20">{children}</main>
      </body>
    </html>
  )
}
 */

"use client"
import { motion } from "framer-motion"
import { FaUser, FaLock } from "react-icons/fa"

export default function LoginPage() {
  return (
    <div className="relative w-full h-screen flex items-center justify-center">
      <motion.div
        initial={{ opacity: 0, scale: 0.9 }}
        animate={{ opacity: 1, scale: 1 }}
        transition={{ duration: 0.6 }}
        className="bg-white/20 backdrop-blur-md rounded-xl p-10 w-full max-w-sm shadow-2xl border 
        border-white/30"
      >
        <div className="flex flex-col items-center mb-6">
          <div className="w-20 h-20 rounded-full bg-white/30 flex items-center justify-center 
          text-white text-3xl mb-4">
            <FaUser />
          </div>
        </div>

        <div className="mb-4 relative">
          <FaUser className="absolute left-3 top-1/2 transform -translate-y-1/2 text-white/70" />
          <input
            type="text"
            placeholder="Username"
            className="w-full pl-10 pr-4 py-2 rounded-md bg-white/30 text-white placeholder-white/70 
            border border-white/40 focus:outline-none focus:ring-2 focus:ring-cyan-400"
          />
        </div>

        <div className="mb-4 relative">
          <FaLock className="absolute left-3 top-1/2 transform -translate-y-1/2 text-white/70" />
          <input
            type="password"
            placeholder="Password"
            className="w-full pl-10 pr-4 py-2 rounded-md bg-white/30 text-white placeholder-white/70 
            border border-white/40 focus:outline-none focus:ring-2 focus:ring-cyan-400"
          />
        </div>

        <div className="flex items-center mb-6">
          <input
            type="checkbox"
            id="remember"
            className="mr-2 accent-cyan-500"
          />
          <label htmlFor="remember" className="text-white text-sm">
            Remember me
          </label>
        </div>

        <button className="w-full py-2 bg-cyan-400 hover:bg-cyan-500 transition-colors text-white 
        font-semibold rounded-md shadow-md">
          LOGIN
        </button>

        <p className="mt-4 text-center text-white text-sm cursor-pointer hover:underline">
          Forgot Username / Password ?
        </p>
      </motion.div>
    </div>
  )
}
