/* import type { Metadata } from "next";
import "./globals.css";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-[url(/background4.jpg)] bg-cover bg-no-repeat">
      {children}
      </body>
    </html>
  );
}
 */

"use client"
import { useGLTF, useAnimations } from "@react-three/drei"
import { useRef, useEffect } from "react"
import { Canvas } from "@react-three/fiber"
import { OrbitControls } from "@react-three/drei"
import { Suspense } from "react"
import { motion } from "framer-motion"


function ModelMan() {
  const group = useRef()
  const { scene, animations } = useGLTF("/model-man.glb")
  const { actions } = useAnimations(animations, group)

  useEffect(() => {
    if (actions["Take 001"]) {
      actions["Take 001"].play()
      actions["Take 001"].timeScale = 0.5
    }
  }, [actions])

  return (
    <primitive
      ref={group}
      object={scene}
      scale={[1, 1, 1]}
      position={[0, 0, 0]}
    />
  )
}

const ModelManView = () => {
    return (
      <motion.div
        className="w-full h-full"
        initial={{ opacity: 0, y: 0 }}
        whileInView={{ opacity: 1, y: 0 }}
        transition={{ duration: 1 }}
      >
        <Canvas
          className="w-full h-full"
          camera={{ position: [0, 2, 5], fov: 30 }}
        >
          <ambientLight intensity={0.5} />
          <directionalLight position={[10, 10, 5]} intensity={1} />
          <Suspense fallback={null}>
            <ModelMan />
          </Suspense>
          <OrbitControls
            target={[0, 1, 0]}
            enableZoom={false}
            enablePan={false}
            minPolarAngle={Math.PI / 2}
            maxPolarAngle={Math.PI / 2}
          />
        </Canvas>
      </motion.div>
    )
  }
  

  export default function Home() {
    return (
       <div className="relative w-full h-[100vh]">
         <div className="absolute top-0 left-0 w-full h-full z-0 mt-10">
           <ModelManView />
         </div>
       </div>
    )
    }