/* import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
title: "ASMR Miko",
description: "Generated by create next app",
};

export default function RootLayout({
children,
}: Readonly<{
children: React.ReactNode;
}>) {
return (
   <html lang="en">
     <body className="bg-[url(/background.png)] bg-cover">
     {children}</body>
   </html>
);
} */


"use client"
import { useGLTF } from "@react-three/drei"
import { useRef } from "react"
import { useFrame } from "@react-three/fiber"
import { Canvas } from "@react-three/fiber"
import { OrbitControls } from "@react-three/drei"
import { Suspense } from "react"

function Model() {
const { scene } = useGLTF("/model.glb")
const modelRef = useRef()

// Automatyczne obracanie modelu w osi Y
useFrame(() => {
   if (modelRef.current) {
     modelRef.current.rotation.y += 0.001 // Możesz dostosować prędkość obrotu
   }
})

return <primitive ref={modelRef} object={scene} scale={[1, 1, 1]} />
}

const ModelView = () => {
return (
   <Canvas camera={{ position: [5, 0, 7], fov: 78 }} className="w-full h-full">
     <Suspense fallback={null}>
       <ambientLight intensity={1} />
       <directionalLight position={[0, 7, 5]} intensity={5} />
       <pointLight position={[0, 5, 5]} intensity={2} />
       <Model />
       <OrbitControls enableRotate={true} enableZoom={true} />
     </Suspense>
   </Canvas>
)
}

export default function Home() {
return (
   <div className="relative w-full h-[100vh]">
     <div className="absolute top-0 left-0 w-full h-full z-0">
       <ModelView />
     </div>
   </div>
)
}