/* import type { Metadata } from "next"
import "./globals.css"
import Navbar from "./Navbar"

export const metadata: Metadata = {
  title: "Application",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <main className="pt-24">{children}</main>
      </body>
    </html>
  )
}
 */

/* "use client"

import { motion } from "framer-motion"
import Link from "next/link"

export default function Navbar() {
return (
   <nav className="w-full bg-white shadow-md fixed top-0 left-0 z-50">
     <div className="max-w-6xl mx-auto flex justify-between items-center 
     py-4 px-6">
       <Link href="/">
         <span className="text-xl font-bold text-gray-900">
           HealthyRecipes
         </span>
       </Link>

       <div className="hidden md:flex space-x-6 items-center">
         <Link
           href=""
           className="text-gray-700 hover:text-gray-900 transition"
         >
           Featured
         </Link>
         <Link
           href=""
           className="text-gray-700 hover:text-gray-900 transition"
         >
           Why Us
         </Link>
         <Link
           href=""
           className="text-gray-700 hover:text-gray-900 transition"
         >
           Testimonials
         </Link>
         <motion.button
           className="px-4 py-2 bg-gray-900 text-white rounded-full 
           shadow-md hover:scale-105 hover:shadow-lg transition"
           whileTap={{ scale: 0.95 }}
         >
           Get Started
         </motion.button>
       </div>
     </div>
   </nav>
)
} */

"use client"
import { motion, AnimatePresence } from "framer-motion"
import { useState, useEffect } from "react"
import Image from "next/image"

const testimonials = [
  {
    name: "Anna, Food Lover",
    text: "This app changed the way I cook! Now I eat healthy every day without spending hours in the kitchen.",
  },
  {
    name: "Tom, Chef",
    text: "Finally a quick way to get nutritious meals ready. Love it!",
  },
  {
    name: "Sara, Student",
    text: "Perfect for my busy schedule. Healthy recipes in minutes!",
  },
]

const whyChooseUs = [
  { title: "Healthy", desc: "Nutritious meals made easy.", icon: "🥗" },
  { title: "Quick", desc: "Recipes under 20 minutes.", icon: "⏱️" },
  { title: "Delicious", desc: "Tasty food you'll love.", icon: "🍴" },
]

const photosTiles = [
  { title: "Avocado Toast", img: "/AvocadoToast.jpg" },
  { title: "Quinoa Salad", img: "/QuinoaSalad.jpg" },
  { title: "Smoothie Bowl", img: "/SmoothieBowl.jpg" },
]

export default function Home() {
  const [testimonialIndex, setTestimonialIndex] = useState(0)

  useEffect(() => {
    const interval = setInterval(() => {
      setTestimonialIndex((prev) => (prev + 1) % testimonials.length)
    }, 5000)
    return () => clearInterval(interval)
  }, [])

  return (
    <main className="flex min-h-screen flex-col items-center 
    justify-center bg-white p-6 text-gray-800">
      {/* HERO */}
      <section className="w-full max-w-6xl text-center mb-16">
        <motion.h1
          className="text-4xl sm:text-6xl font-extrabold text-gray-900 
          drop-shadow-md"
          initial={{ opacity: 0, y: -40 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6 }}
        >
          Healthy Recipes App 🥗
        </motion.h1>
        <motion.p
          className="mt-4 text-gray-700 text-lg max-w-2xl mx-auto"
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ delay: 0.4 }}
        >
          Discover quick, healthy and delicious recipes tailored just 
          for you. Eat better, live better.
        </motion.p>
        <motion.button
          className="mt-6 px-6 py-3 bg-gray-900 text-white font-semibold 
          rounded-full shadow-md hover:scale-105 transition"
          whileTap={{ scale: 0.9 }}
        >
          Get Started
        </motion.button>
      </section>

      {/* FEATURED RECIPES */}
      <section className="w-full max-w-6xl mb-16">
        <h2 className="text-2xl font-bold text-gray-900 mb-6 text-center">
          Featured Recipes
        </h2>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
          {photosTiles.map((recipe, idx) => (
            <motion.div
              key={idx}
              className="rounded-xl overflow-hidden bg-gray-50 shadow 
              hover:shadow-xl transition cursor-pointer h-64"
              whileHover={{ scale: 1.03 }}
            >
              <Image
                src={recipe.img}
                alt={recipe.title}
                width={600}
                height={400}
                className="h-48 w-full object-cover"
              />
              <div className="p-4 text-gray-900 font-semibold">
                {recipe.title}
              </div>
            </motion.div>
          ))}
        </div>
      </section>

      {/* WHY CHOOSE US */}
      <section className="w-full max-w-6xl mb-16">
        <h2 className="text-2xl font-bold text-gray-900 mb-6 text-center">
          Why Choose Us?
        </h2>
        <div className="grid grid-cols-1 sm:grid-cols-3 gap-6">
          {whyChooseUs.map((item, idx) => (
            <motion.div
              key={idx}
              className="p-6 rounded-xl bg-gray-50 text-center shadow-md 
              h-48 flex flex-col justify-center items-center"
              whileHover={{ scale: 1.03, y: -2 }}
            >
              <div className="text-2xl mb-2">{item.icon}</div>
              <h3 className="text-lg font-semibold mb-2">{item.title}</h3>
              <p className="text-sm text-gray-700">{item.desc}</p>
            </motion.div>
          ))}
        </div>
      </section>

      {/* TESTIMONIAL SLIDER */}
      <section className="w-full max-w-3xl mb-16 text-center">
        <AnimatePresence mode="wait">
          <motion.div
            key={testimonialIndex}
            className="p-6 rounded-2xl bg-gray-50 shadow-md h-48 flex 
            flex-col justify-center"
            initial={{ opacity: 0, x: 100 }}
            animate={{ opacity: 1, x: 0 }}
            exit={{ opacity: 0, x: -100 }}
            transition={{ duration: 0.5 }}
          >
            <p className="text-gray-900 text-lg italic">
              {testimonials[testimonialIndex].text}
            </p>
            <div className="mt-4 font-semibold text-gray-900">
              — {testimonials[testimonialIndex].name}
            </div>
          </motion.div>
        </AnimatePresence>
      </section>

      {/* CTA */}
      <section className="mb-12 text-center">
        <motion.button
          className="px-8 py-3 bg-gray-900 text-white font-bold 
          rounded-full shadow-lg hover:scale-105 transition"
          whileTap={{ scale: 0.9 }}
        >
          Download App
        </motion.button>
      </section>

      {/* FOOTER */}
      <footer className="text-gray-500 text-sm text-center mb-4">
        Designed with 🍃 using Next.js · TailwindCSS · Framer Motion
      </footer>
    </main>
  )
}
