/* import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
title: "Create Next App",
description: "Generated by create next app",
};

export default function RootLayout({
children,
}: Readonly<{
children: React.ReactNode;
}>) {
return (
   <html lang="en">
     <body className="bg-[url(/image4.jpg)] bg-[100vw,100vh] bg-no-repeat">{children}</body>
   </html>
);
} */

'use client'
import { useState } from "react";

export default function Calculator() {
const [input, setInput] = useState<string>("");

const handleButtonClick = (value: string) => {
   if (value === "C") {
     setInput("");
   } else if (value === "=") {
     try {
       setInput(eval(input).toString());
     } catch {
       setInput("Error");
     }
   } else {
     setInput(input + value);
   }
};

const buttons = [
   "7", "8", "9", "/",
   "4", "5", "6", "*",
   "1", "2", "3", "-",
   "0", ".", "=", "+",
   "C"
];

return (
   <div className="min-h-screen flex items-center justify-center p-4">
     <div className="bg-white rounded-3xl shadow-2xl p-6 w-80">
       <div className="mb-4 text-right text-2xl font-semibold text-gray-700 
       bg-purple-50 rounded-xl p-3 shadow-inner">
         {input || "0"}
       </div>
       <div className="grid grid-cols-4 gap-3">
         {buttons.map((btn) => (
           <button
             key={btn}
             onClick={() => handleButtonClick(btn)}
             className="bg-purple-100 hover:bg-purple-200 active:bg-purple-300 
             text-gray-800 font-medium py-3 rounded-xl shadow transition-all 
             duration-200"
           >
             {btn}
           </button>
         ))}
       </div>
     </div>
   </div>
);
}